version: "3.8"

services:
  # FastAPI Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: ecohire-api
    image: ecohire-api
    environment:
      - MONGODB_URL=${}
      - DATABASE_NAME=${}
      - GEMINI_API_KEY=${}
    volumes:
      - .:/app
    restart: unless-stopped
